### ISSUE TITLE
Nicer website

### ISSUE THREAD

**Issue by haselkern** [jsonmc/jsonmc#104]
[The website](https://jsonmc.github.io/) of this project, while working, is not really pretty. I'm willing to come up with a nicer design, but cannot find out where to contribute to.

Any input on this by @lsmoura?

**Comment by lsmoura** [comment]
Can you check this project https://github.com/jsonmc/website-builder ?

Unfortunately, I lost my old HD with the original site builder...

**Comment by haselkern** [comment]
That's unfortunate! But thanks for uploading the src folder, I will try to come up with a way to support nicer websites.

**Comment by lsmoura** [comment]
Working on this issue on the other repo.
