### ISSUE TITLE
Add Spiderman Movies

### ISSUE THREAD

**Issue by nikhilbansal97** [jsonmc/jsonmc#110]

**Comment by nikhilbansal97** [comment]
I am working on it

**Comment by lsmoura** [comment]
@nikhilbansal97 Remember to put "closes #110" somewhere on your PR commit message so that this task gets closed automatically and you get credited for your work for Hacktoberfest.

**Comment by nikhilbansal97** [comment]
okay @lsmoura ! I will remember it next time! :smile:

**Comment by nikhilbansal97** [comment]
I have updated my PR
