### ISSUE TITLE
Finding Forrester (2000)

### ISSUE THREAD

**Issue by lsmoura** [jsonmc/jsonmc#118]

**Comment by emilyy1231** [comment]
Ooo, I got it!

**Comment by emilyy1231** [comment]
I'm relatively new to programming, so I was just wondering what this JSON could potentially be used for? Couldn't you just parse and store all the movies on IMDB?

**Comment by jhugobb** [comment]
Did not find the PR that you mention, is it ok if I submit my own?

**Comment by emilyy1231** [comment]
@jhugobb Hmm, I'm pretty sure I made a pull request. Let me double check.

**Comment by jhugobb** [comment]
If you forked the repository make sure you made the pull request in this repo and not on your own :D @emilyy1231

**Comment by emilyy1231** [comment]
@jhugobb it says "emilyy1231 wants to merge 1 commit into master from emilyy1231-patch-1", so I think I did it right - let me know!
![finding_forrester_pr](https://user-images.githubusercontent.com/13202095/31916941-1794daa0-b823-11e7-91ab-a56e74ded652.png)

**Comment by jhugobb** [comment]
Thats your repository, note that the name above says "emilyy1231/jsonmc". That's because that is your version of it. You need to go to the jsonmc/jsonmc repo (aka this one) and submit a pull request between forks. Then something in here should say you opened one if you mention "Issue #118" in the PR description. @emilyy1231

**Comment by emilyy1231** [comment]
@jhugobb Ahhhh, thank you thank you. Just submitted the pull request.

**Comment by jhugobb** [comment]
There you go 👍 don't forget to put the "Fixes #118" in the description of the PR so it can be linked to here and identified for Hacktoberfest! @emilyy1231
