### ISSUE TITLE
Add 2018 marvel movies

### ISSUE THREAD

**Issue by lsmoura** [jsonmc/jsonmc#189]
Only 2018 movies. Other years should come in separate Issues / PRs.

**Comment by karan919** [comment]
I like to work on this.

**Comment by lsmoura** [comment]
Go ahead, @karan919 !

**Comment by mohancm** [comment]
@lsmoura  done here #208

**Comment by mohancm** [comment]
Sorry @karan919 I didn't know, that we have to inform them before making pr
