### ISSUE TITLE
You don't distinguish between Actors and Actresses. 

### ISSUE THREAD

**Issue by steaward** [jsonmc/jsonmc#234]
For instance, Charlizee Theron is not an actor, she is an actress. Gender equality is a big issue in this day and world. 

Can I fix this?

**Comment by lsmoura** [comment]
How do you propose this fix? I don't really want a per-gender folder...

**Comment by MineRobber9000** [comment]
using the term "actor" fits; as it means "one who acts". just because it's usually used for males only doesn't mean it's a male-only term that needs to be removed because "gender equality".

I propose that the files are left as is.

**Comment by lsmoura** [comment]
Keeping as-is. Thanks @MineRobber9000 !
