### ISSUE TITLE
Add support for multiple directors

### ISSUE THREAD

**Issue by mattgd** [jsonmc/jsonmc#24]
Might be good to rename director to directors like the actors array as some movies have multiple directors.

Example:
```
"directors": [
     "Lana Wachowski",
     "Lilly Wachowski",
     "Yoshiaki Kawajiri"
  ]
```

**Comment by lsmoura** [comment]
That's already documented on `contributing.markdown`. It should be a single string if there is only one and an array if there are more than one. The key (director) should be singular, tough...

Your example is valid, you just need to keep the key name singular (director).
