### ISSUE TITLE
Improve test: Movies required fields

### ISSUE THREAD

**Issue by lsmoura** [jsonmc/jsonmc#289]
All movies must have:
* name
* year
* runtime

**Comment by tarunjindal790** [comment]
Can I work on this? :)

**Comment by tarunjindal790** [comment]
Sorry...dibs.

**Comment by lsmoura** [comment]
@tarunjindal790 Go ahead!

**Comment by tarunjindal790** [comment]
I have created a pull request at #336 for the issue. :)
