### ISSUE TITLE
Improve test: All json filenames must be all lowercase

### ISSUE THREAD

**Issue by lsmoura** [jsonmc/jsonmc#295]
A simple test would be comparing each filename string with the `filename.toLowerCase()` and make sure they are the same.

**Comment by ShawnToubeau** [comment]
Hello! Mind if I take this one on? What are you using to run the tests?

**Comment by lsmoura** [comment]
@ShawnToubeau Just manual asserts. Nothing fancy. No libraries or anything...

**Comment by ShawnToubeau** [comment]
In class right now but I should be able to knock it out later today if that is okay?

**Comment by lsmoura** [comment]
@ShawnToubeau Sure! I'll review more PRs tonight and tomorrow.
