### ISSUE TITLE
Add instructions for movies yet to be released

### ISSUE THREAD

**Issue by wadleo** [jsonmc/jsonmc#35]
While working on #21 Underworld movies, I discover that they have to make a release next year (Underworld: Blood wars). So I was wondering if we could include such data here. Also, because much details about such movies is not yet available like the runtime.

**Comment by lsmoura** [comment]
Go for it! I'll add details the documentation tonight, but do not let this stop you.

**Comment by lsmoura** [comment]
Fixed.
