### ISSUE TITLE
Create tests for directors

### ISSUE THREAD

**Issue by lsmoura** [jsonmc/jsonmc#553]
Essentially the same as for actors.

Eventually I'll drop the directors and actors folders and just add put everybody inside "people"... but not today.

**Comment by AlexandruValeanu** [comment]
May I take this?

**Comment by lsmoura** [comment]
@AlexandruValeanu It's yours!

**Comment by CKIWilkinson** [comment]
I've already opened an [issue](https://github.com/jsonmc/jsonmc/issues/506) and a [PR](https://github.com/jsonmc/jsonmc/pull/528) for this

**Comment by lsmoura** [comment]
@CKIWilkinson I just saw it. My bad. Too many PRs!

**Comment by lsmoura** [comment]
@AlexandruValeanu This is duplicated. Sorry about that.
