### ISSUE TITLE
Marvel Movies

### ISSUE THREAD

**Issue by lsmoura** [jsonmc/jsonmc#6]
This is just a placeholder. Check the "referenced" issues.

If there is a marvel movie or collection that you feel it's left out, reference this issue, please.

**Comment by nikhilbansal97** [comment]
Can I open an issue for some other series of movies?

**Comment by lsmoura** [comment]
Oh yeah! I’ll tag them Hacktoberfest and merge them only in October.

**Comment by nikhilbansal97** [comment]
okay..cool :+1:

**Comment by giu-lia** [comment]
i'm gonna add guardians of the galaxy right away :D

**Comment by lsmoura** [comment]
Thanks for all contributions!
